"""Stable dependency-free domain contracts for PokeApp 2.0."""

from app.domain.activity import ActivityEvent, ActivityEventType
from app.domain.archives import SeasonArchive
from app.domain.common import (
    ActivityEventId,
    CupId,
    DivisionId,
    HallOfFameEntryId,
    JsonObject,
    JsonValue,
    MatchId,
    MatchdayId,
    PokemonId,
    PurchaseId,
    RedemptionId,
    SaveId,
    SeasonArchiveId,
    SeasonId,
    SeasonPlayerId,
    SeasonVersionId,
    ShopItemId,
    ShopPromotionId,
    TeamLockId,
    TrainerId,
    TrialId,
    UtcTimestamp,
    Visibility,
    to_jsonable,
)
from app.domain.cup import Cup, CupFormat, CupMatch
from app.domain.hall_of_fame import HallOfFameEntry
from app.domain.league import (
    LeagueStanding,
    Match,
    MatchStatus,
    Matchday,
    MatchdaySnapshot,
    MatchdayStatus,
)
from app.domain.pokemon import (
    PokemonFlags,
    PokemonMove,
    PrivatePokemon,
    PublicPokemon,
    StatSpread,
)
from app.domain.saves import (
    BoxSlot,
    InventoryItem,
    ParsedSave,
    PartySlot,
    PokemonBox,
    SaveRecord,
)
from app.domain.seasons import (
    Division,
    Season,
    SeasonLifecycle,
    SeasonMetadata,
    SeasonPlayer,
    SeasonRules,
    SeasonVersion,
)
from app.domain.shop import (
    Purchase,
    PurchaseStatus,
    Redemption,
    ShopItem,
    ShopPromotion,
)
from app.domain.team_locks import TeamLock
from app.domain.trainers import Trainer, TrainerFlags, TrainerStatus
from app.domain.trials import Penalty, PenaltyType, TrialCase, TrialStatus, TrialVerdict

__all__ = [
    "ActivityEvent",
    "ActivityEventId",
    "ActivityEventType",
    "BoxSlot",
    "Cup",
    "CupFormat",
    "CupId",
    "CupMatch",
    "Division",
    "DivisionId",
    "HallOfFameEntry",
    "HallOfFameEntryId",
    "InventoryItem",
    "JsonObject",
    "JsonValue",
    "LeagueStanding",
    "Match",
    "MatchId",
    "MatchStatus",
    "Matchday",
    "MatchdayId",
    "MatchdaySnapshot",
    "MatchdayStatus",
    "ParsedSave",
    "PartySlot",
    "Penalty",
    "PenaltyType",
    "PokemonBox",
    "PokemonFlags",
    "PokemonId",
    "PokemonMove",
    "PrivatePokemon",
    "PublicPokemon",
    "Purchase",
    "PurchaseId",
    "PurchaseStatus",
    "Redemption",
    "RedemptionId",
    "SaveId",
    "SaveRecord",
    "Season",
    "SeasonArchive",
    "SeasonArchiveId",
    "SeasonId",
    "SeasonLifecycle",
    "SeasonMetadata",
    "SeasonPlayer",
    "SeasonPlayerId",
    "SeasonRules",
    "SeasonVersion",
    "SeasonVersionId",
    "ShopItemId",
    "ShopItem",
    "ShopPromotionId",
    "ShopPromotion",
    "StatSpread",
    "TeamLockId",
    "TeamLock",
    "Trainer",
    "TrainerFlags",
    "TrainerId",
    "TrainerStatus",
    "TrialCase",
    "TrialId",
    "TrialStatus",
    "TrialVerdict",
    "UtcTimestamp",
    "Visibility",
    "to_jsonable",
]
