-- ONLY FOR EMPTY POKEAPP V2 DATABASE.
--
-- Generated operational bootstrap for Supabase SQL Editor.
-- Source of truth: supabase/v2/migrations/001_core.sql through 018_public_views_visibility.sql.
-- Do not edit this file manually; regenerate it with:
--   py tools/generate_supabase_v2_bootstrap.py
--
-- This file intentionally excludes the destructive development reset.
-- It contains no destructive reset statements and is not a reset script.

-- ============================================================================
-- BEGIN 001_core.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 001_core: extensions, shared helpers, global trainers and seasons.
-- Intended for an empty Supabase/Postgres database, not for patching V1.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_settings_key_format_chk
    check (key ~ '^[a-z0-9][a-z0-9_.:-]*$')
);

create trigger app_settings_set_updated_at
before update on public.app_settings
for each row execute function public.set_updated_at();

comment on table public.app_settings is
  'Small technical/global settings only. Never store league state, snapshots, Hall, trainer status or saves here.';

create table public.trainers (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  slug text not null unique,
  auth_user_id uuid unique,
  globally_enabled boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trainers_display_name_non_empty_chk
    check (length(btrim(display_name)) > 0),
  constraint trainers_slug_format_chk
    check (slug = lower(slug) and slug ~ '^[a-z0-9][a-z0-9_-]*$')
);

create trigger trainers_set_updated_at
before update on public.trainers
for each row execute function public.set_updated_at();

comment on table public.trainers is
  'Global trainer identity. Season status, robbed flags, points, coins and divisions live elsewhere.';
comment on column public.trainers.auth_user_id is
  'Prepared for Supabase Auth/RLS. No FK to auth.users in V2 SQL so local Postgres builds remain reproducible.';

create table public.seasons (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  status text not null default 'draft',
  created_by_trainer_id uuid references public.trainers(id) on delete set null,
  started_at timestamptz,
  finished_at timestamptz,
  archived_at timestamptz,
  discarded_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint seasons_name_non_empty_chk
    check (length(btrim(name)) > 0),
  constraint seasons_status_chk
    check (status in ('draft', 'active', 'finished', 'archived', 'discarded')),
  constraint seasons_lifecycle_timestamp_chk
    check (
      (status <> 'active' or started_at is not null)
      and (status <> 'finished' or finished_at is not null)
      and (status <> 'archived' or archived_at is not null)
      and (status <> 'discarded' or discarded_at is not null)
    )
);

create trigger seasons_set_updated_at
before update on public.seasons
for each row execute function public.set_updated_at();

comment on table public.seasons is
  'Real live/historical season. Archiving sets status=archived; relational data remains in place.';

commit;
-- ============================================================================
-- END 001_core.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 002_seasons.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 002_seasons: season participants, stats, config versions and divisions.

begin;

create table public.season_players (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  trainer_id uuid not null references public.trainers(id) on delete restrict,
  status text not null default 'active',
  seed_order integer,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  current_save_file_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint season_players_status_chk
    check (status in ('active', 'retired', 'abandoned', 'disqualified')),
  constraint season_players_seed_order_chk
    check (seed_order is null or seed_order > 0),
  constraint season_players_left_after_join_chk
    check (left_at is null or left_at >= joined_at),
  constraint uq_season_players_season_trainer
    unique (season_id, trainer_id),
  constraint uq_season_players_id_season
    unique (id, season_id),
  constraint uq_season_players_id_season_trainer
    unique (id, season_id, trainer_id)
);

create trigger season_players_set_updated_at
before update on public.season_players
for each row execute function public.set_updated_at();

comment on table public.season_players is
  'Trainer participation in a season. Current season status lives here, not on trainers.';
comment on column public.season_players.current_save_file_id is
  'Added as nullable now; the FK to save_files is added in 005_saves after save_files exists.';

create table public.season_player_stats (
  season_player_id uuid primary key,
  season_id uuid not null,
  trainer_id uuid not null,
  badges_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint season_player_stats_badges_chk
    check (badges_count >= 0),
  constraint fk_season_player_stats_player
    foreign key (season_player_id, season_id, trainer_id)
    references public.season_players(id, season_id, trainer_id)
    on delete restrict
);

create trigger season_player_stats_set_updated_at
before update on public.season_player_stats
for each row execute function public.set_updated_at();

comment on table public.season_player_stats is
  'Season-scoped lightweight trainer stats such as badges. Coins are not stored here; they come from coin_transactions.';

create table public.trainer_flags (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null,
  trainer_id uuid not null,
  season_player_id uuid not null,
  flag_type text not null,
  flag_value boolean not null default true,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trainer_flags_type_chk
    check (flag_type = lower(flag_type) and flag_type ~ '^[a-z0-9_]+$'),
  constraint uq_trainer_flags_season_trainer_type
    unique (season_id, trainer_id, flag_type),
  constraint fk_trainer_flags_player_same_owner
    foreign key (season_player_id, season_id, trainer_id)
    references public.season_players(id, season_id, trainer_id)
    on delete restrict
);

create trigger trainer_flags_set_updated_at
before update on public.trainer_flags
for each row execute function public.set_updated_at();

comment on table public.trainer_flags is
  'Season-scoped trainer flags such as robbed. Competitive status remains in season_players.status.';

create table public.pokemon_flags (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null,
  trainer_id uuid not null,
  season_player_id uuid not null,
  fingerprint text not null,
  flag_type text not null,
  flag_value boolean not null default true,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pokemon_flags_fingerprint_chk
    check (length(btrim(fingerprint)) > 0),
  constraint pokemon_flags_type_chk
    check (flag_type = lower(flag_type) and flag_type ~ '^[a-z0-9_]+$'),
  constraint uq_pokemon_flags_season_owner_fingerprint_type
    unique (season_id, trainer_id, fingerprint, flag_type),
  constraint fk_pokemon_flags_player_same_owner
    foreign key (season_player_id, season_id, trainer_id)
    references public.season_players(id, season_id, trainer_id)
    on delete restrict
);

create trigger pokemon_flags_set_updated_at
before update on public.pokemon_flags
for each row execute function public.set_updated_at();

comment on table public.pokemon_flags is
  'Season-scoped Pokemon flags. Fingerprint is the stable Pokemon identity until the parser exposes a stronger id.';

create table public.season_config_versions (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  version_number integer not null,
  name text not null,
  effective_from_matchday integer not null,
  total_matchdays integer not null,
  division_count integer not null,
  promotion_relegation_count integer not null default 0,
  scoring_json jsonb not null default '{}'::jsonb,
  coin_rewards_json jsonb not null default '{}'::jsonb,
  rules_json jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  locked_at timestamptz,
  created_by_trainer_id uuid references public.trainers(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint season_config_versions_number_chk
    check (version_number > 0),
  constraint season_config_versions_name_chk
    check (length(btrim(name)) > 0),
  constraint season_config_versions_effective_chk
    check (effective_from_matchday > 0),
  constraint season_config_versions_total_matchdays_chk
    check (total_matchdays > 0),
  constraint season_config_versions_division_count_chk
    check (division_count > 0),
  constraint season_config_versions_movement_chk
    check (promotion_relegation_count >= 0),
  constraint uq_season_config_versions_season_number
    unique (season_id, version_number),
  constraint uq_season_config_versions_season_effective
    unique (season_id, effective_from_matchday),
  constraint uq_season_config_versions_id_season
    unique (id, season_id)
);

comment on table public.season_config_versions is
  'Versioned season configuration. Used matchdays point to the exact config version so history is not reinterpreted.';

create table public.divisions (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  code text not null,
  name text not null,
  tier_order integer not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint divisions_code_chk
    check (code = upper(code) and code ~ '^[A-Z0-9_-]+$'),
  constraint divisions_name_chk
    check (length(btrim(name)) > 0),
  constraint divisions_tier_order_chk
    check (tier_order > 0),
  constraint uq_divisions_season_code
    unique (season_id, code),
  constraint uq_divisions_season_tier
    unique (season_id, tier_order),
  constraint uq_divisions_id_season
    unique (id, season_id)
);

comment on table public.divisions is
  'Season divisions. Supports A/B today and more tiers later without changing identity.';

commit;
-- ============================================================================
-- END 002_seasons.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 003_league.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 003_league: matchdays, matches, division history, snapshots and movements.

begin;

create table public.matchdays (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  number integer not null,
  status text not null default 'scheduled',
  season_config_version_id uuid not null,
  opened_at timestamptz,
  closed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchdays_number_chk
    check (number > 0),
  constraint matchdays_status_chk
    check (status in ('scheduled', 'open', 'closed', 'cancelled')),
  constraint matchdays_closed_timestamp_chk
    check (status <> 'closed' or closed_at is not null),
  constraint uq_matchdays_season_number
    unique (season_id, number),
  constraint uq_matchdays_id_season
    unique (id, season_id),
  constraint fk_matchdays_config_same_season
    foreign key (season_config_version_id, season_id)
    references public.season_config_versions(id, season_id)
    on delete restrict
);

create trigger matchdays_set_updated_at
before update on public.matchdays
for each row execute function public.set_updated_at();

comment on table public.matchdays is
  'Official matchday/jornada. Closed matchdays keep their config version and snapshot.';

create table public.division_memberships (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  season_player_id uuid not null,
  division_id uuid not null,
  effective_from_matchday_number integer not null,
  effective_to_matchday_number integer,
  source_matchday_id uuid,
  reason text not null default 'initial',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint division_memberships_from_chk
    check (effective_from_matchday_number > 0),
  constraint division_memberships_to_chk
    check (
      effective_to_matchday_number is null
      or effective_to_matchday_number >= effective_from_matchday_number
    ),
  constraint division_memberships_reason_chk
    check (reason in ('initial', 'promotion', 'relegation', 'admin', 'status_change')),
  constraint uq_division_memberships_player_from
    unique (season_player_id, effective_from_matchday_number),
  constraint fk_division_memberships_player_same_season
    foreign key (season_player_id, season_id)
    references public.season_players(id, season_id)
    on delete restrict,
  constraint fk_division_memberships_division_same_season
    foreign key (division_id, season_id)
    references public.divisions(id, season_id)
    on delete restrict,
  constraint fk_division_memberships_source_matchday_same_season
    foreign key (source_matchday_id, season_id)
    references public.matchdays(id, season_id)
    on delete restrict
);

comment on table public.division_memberships is
  'Historical division membership. Do not overwrite current division in season_players and lose history.';

create table public.matches (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null,
  matchday_id uuid not null,
  division_id uuid not null,
  player_a_id uuid not null,
  player_b_id uuid not null,
  winner_id uuid,
  status text not null default 'scheduled',
  result_code text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matches_status_chk
    check (status in ('scheduled', 'completed', 'forfeit', 'void')),
  constraint matches_players_different_chk
    check (player_a_id <> player_b_id),
  constraint matches_winner_is_player_chk
    check (winner_id is null or winner_id = player_a_id or winner_id = player_b_id),
  constraint uq_matches_matchday_pair
    unique (matchday_id, division_id, player_a_id, player_b_id),
  constraint fk_matches_matchday_same_season
    foreign key (matchday_id, season_id)
    references public.matchdays(id, season_id)
    on delete restrict,
  constraint fk_matches_division_same_season
    foreign key (division_id, season_id)
    references public.divisions(id, season_id)
    on delete restrict,
  constraint fk_matches_player_a_same_season
    foreign key (player_a_id, season_id)
    references public.season_players(id, season_id)
    on delete restrict,
  constraint fk_matches_player_b_same_season
    foreign key (player_b_id, season_id)
    references public.season_players(id, season_id)
    on delete restrict,
  constraint fk_matches_winner_same_season
    foreign key (winner_id, season_id)
    references public.season_players(id, season_id)
    on delete restrict
);

create trigger matches_set_updated_at
before update on public.matches
for each row execute function public.set_updated_at();

comment on table public.matches is
  'Actual league matches. Only stores data PokeApp uses: players, winner/status and metadata.';

create table public.matchday_snapshots (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null,
  matchday_id uuid not null,
  config_version_id uuid not null,
  revision integer not null default 1,
  snapshot_schema_version integer not null default 1,
  closed_at timestamptz not null,
  snapshot jsonb not null,
  created_by_trainer_id uuid references public.trainers(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matchday_snapshots_revision_chk
    check (revision > 0),
  constraint matchday_snapshots_schema_version_chk
    check (snapshot_schema_version > 0),
  constraint uq_matchday_snapshots_matchday
    unique (matchday_id),
  constraint fk_matchday_snapshots_matchday_same_season
    foreign key (matchday_id, season_id)
    references public.matchdays(id, season_id)
    on delete restrict,
  constraint fk_matchday_snapshots_config_same_season
    foreign key (config_version_id, season_id)
    references public.season_config_versions(id, season_id)
    on delete restrict
);

create trigger matchday_snapshots_set_updated_at
before update on public.matchday_snapshots
for each row execute function public.set_updated_at();

comment on table public.matchday_snapshots is
  'One official closed snapshot per matchday. Admin recompute should update this row and increment revision explicitly.';

create table public.matchday_movements (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null,
  matchday_id uuid not null,
  season_player_id uuid not null,
  from_division_id uuid,
  to_division_id uuid,
  movement_type text not null,
  reason text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint matchday_movements_type_chk
    check (movement_type in ('promotion', 'relegation', 'stay', 'admin')),
  constraint fk_matchday_movements_matchday_same_season
    foreign key (matchday_id, season_id)
    references public.matchdays(id, season_id)
    on delete restrict,
  constraint fk_matchday_movements_player_same_season
    foreign key (season_player_id, season_id)
    references public.season_players(id, season_id)
    on delete restrict,
  constraint fk_matchday_movements_from_division_same_season
    foreign key (from_division_id, season_id)
    references public.divisions(id, season_id)
    on delete restrict,
  constraint fk_matchday_movements_to_division_same_season
    foreign key (to_division_id, season_id)
    references public.divisions(id, season_id)
    on delete restrict
);

comment on table public.matchday_movements is
  'Official promotions/relegations/stays for queries and Discord/API summaries. Full closed state also remains in matchday_snapshots.';

commit;
-- ============================================================================
-- END 003_league.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 004_shop.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 004_shop: catalog, promotions, purchases, redemptions and coin ledger.

begin;

create table public.shop_items (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  category text not null,
  description text not null default '',
  base_price integer not null,
  enabled boolean not null default true,
  image_key text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_items_code_chk
    check (code = lower(code) and code ~ '^[a-z0-9][a-z0-9_-]*$'),
  constraint shop_items_name_chk
    check (length(btrim(name)) > 0),
  constraint shop_items_category_chk
    check (category in ('comodines', 'bayas', 'competitivos', 'crianza', 'other')),
  constraint shop_items_base_price_chk
    check (base_price >= 0)
);

create trigger shop_items_set_updated_at
before update on public.shop_items
for each row execute function public.set_updated_at();

comment on table public.shop_items is
  'Version-controlled seedable shop catalog. Visible names are not foreign keys.';

create table public.shop_promotions (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  matchday_id uuid references public.matchdays(id) on delete restrict,
  shop_item_id uuid not null references public.shop_items(id) on delete restrict,
  promotion_type text not null,
  status text not null default 'pending',
  base_price integer not null,
  effective_price integer not null,
  stock_total integer not null,
  stock_used integer not null default 0,
  announced_at timestamptz,
  activates_at timestamptz,
  ends_at timestamptz,
  exhausted_at timestamptz,
  dedupe_key text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_promotions_type_chk
    check (promotion_type in ('normal', 'mega')),
  constraint shop_promotions_status_chk
    check (status in ('pending', 'active', 'ended', 'exhausted', 'cancelled')),
  constraint shop_promotions_prices_chk
    check (base_price >= 0 and effective_price >= 0 and effective_price <= base_price),
  constraint shop_promotions_stock_chk
    check (stock_total >= 0 and stock_used >= 0 and stock_used <= stock_total),
  constraint uq_shop_promotions_id_season
    unique (id, season_id),
  constraint fk_shop_promotions_matchday_same_season
    foreign key (matchday_id, season_id)
    references public.matchdays(id, season_id)
    on delete restrict
);

create trigger shop_promotions_set_updated_at
before update on public.shop_promotions
for each row execute function public.set_updated_at();

comment on table public.shop_promotions is
  'Rotating discounts. Future API/RPC must claim stock atomically before inserting purchases.';

create table public.purchases (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null,
  trainer_id uuid not null,
  season_player_id uuid not null,
  shop_item_id uuid not null references public.shop_items(id) on delete restrict,
  promotion_id uuid,
  quantity integer not null default 1,
  unit_price integer not null,
  total_price integer generated always as (quantity * unit_price) stored,
  status text not null default 'pending',
  purchased_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint purchases_quantity_chk
    check (quantity > 0),
  constraint purchases_unit_price_chk
    check (unit_price >= 0),
  constraint purchases_status_chk
    check (status in ('pending', 'used', 'cancelled', 'refunded')),
  constraint uq_purchases_id_season_trainer_item
    unique (id, season_id, trainer_id, shop_item_id),
  constraint fk_purchases_player_same_owner
    foreign key (season_player_id, season_id, trainer_id)
    references public.season_players(id, season_id, trainer_id)
    on delete restrict,
  constraint fk_purchases_promotion_same_season
    foreign key (promotion_id, season_id)
    references public.shop_promotions(id, season_id)
    on delete restrict
);

comment on table public.purchases is
  'Auditable single-item purchases. No purchase_lines until the product needs multi-item carts.';

create table public.redemptions (
  id uuid primary key default gen_random_uuid(),
  purchase_id uuid not null references public.purchases(id) on delete restrict,
  season_id uuid not null,
  trainer_id uuid not null,
  season_player_id uuid not null,
  shop_item_id uuid not null references public.shop_items(id) on delete restrict,
  redemption_type text not null default 'item_use',
  status text not null default 'applied',
  payload jsonb not null default '{}'::jsonb,
  redeemed_at timestamptz not null default now(),
  constraint redemptions_type_chk
    check (length(btrim(redemption_type)) > 0),
  constraint redemptions_status_chk
    check (status in ('applied', 'reverted', 'cancelled')),
  constraint fk_redemptions_purchase_same_owner_item
    foreign key (purchase_id, season_id, trainer_id, shop_item_id)
    references public.purchases(id, season_id, trainer_id, shop_item_id)
    on delete restrict,
  constraint fk_redemptions_player_same_owner
    foreign key (season_player_id, season_id, trainer_id)
    references public.season_players(id, season_id, trainer_id)
    on delete restrict
);

comment on table public.redemptions is
  'Purchase redemption/use audit. Purchase and redemption are intentionally separate.';

create table public.coin_transactions (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null,
  trainer_id uuid not null,
  season_player_id uuid not null,
  amount integer not null,
  transaction_type text not null,
  reference_type text not null default '',
  reference_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_by_trainer_id uuid references public.trainers(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint coin_transactions_amount_chk
    check (amount <> 0),
  constraint coin_transactions_type_chk
    check (transaction_type in ('matchday_reward', 'purchase', 'penalty', 'admin_adjustment', 'compensation')),
  constraint fk_coin_transactions_player_same_owner
    foreign key (season_player_id, season_id, trainer_id)
    references public.season_players(id, season_id, trainer_id)
    on delete restrict
);

comment on table public.coin_transactions is
  'Coin ledger. Balance is sum(amount); cached balances must be reconstructible from this table.';

commit;
-- ============================================================================
-- END 004_shop.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 005_saves.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 005_saves: raw save metadata, parsed save cache, current save and team locks.

begin;

create table public.save_files (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  trainer_id uuid not null references public.trainers(id) on delete restrict,
  storage_bucket text not null default 'raw-saves',
  storage_key text not null unique,
  original_filename text not null,
  sha256 text not null,
  parser_status text not null default 'pending',
  parser_version text not null default '',
  uploaded_at timestamptz not null default now(),
  deleted_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  constraint save_files_storage_bucket_chk
    check (length(btrim(storage_bucket)) > 0),
  constraint save_files_storage_key_chk
    check (length(btrim(storage_key)) > 0),
  constraint save_files_original_filename_chk
    check (length(btrim(original_filename)) > 0),
  constraint save_files_sha256_chk
    check (sha256 ~ '^[a-f0-9]{64}$'),
  constraint save_files_parser_status_chk
    check (parser_status in ('pending', 'parsed', 'failed', 'stale')),
  constraint uq_save_files_id_season_trainer
    unique (id, season_id, trainer_id),
  constraint uq_save_files_trainer_season_sha
    unique (trainer_id, season_id, sha256)
);

comment on table public.save_files is
  'Raw save metadata only. Bytes live in a private storage bucket and paths must not be exposed publicly.';

create table public.parsed_saves (
  id uuid primary key default gen_random_uuid(),
  save_file_id uuid not null references public.save_files(id) on delete restrict,
  parser_version text not null,
  schema_version integer not null default 1,
  parsed_at timestamptz not null default now(),
  status text not null default 'parsed',
  payload jsonb not null,
  metadata jsonb not null default '{}'::jsonb,
  constraint parsed_saves_parser_version_chk
    check (length(btrim(parser_version)) > 0),
  constraint parsed_saves_schema_version_chk
    check (schema_version > 0),
  constraint parsed_saves_status_chk
    check (status in ('parsed', 'failed')),
  constraint uq_parsed_saves_file_parser
    unique (save_file_id, parser_version)
);

comment on table public.parsed_saves is
  'Parser payload/cache. Reparse with a new parser_version without mutating the raw save.';

alter table public.season_players
  add constraint fk_season_players_current_save_same_owner
  foreign key (current_save_file_id, season_id, trainer_id)
  references public.save_files(id, season_id, trainer_id)
  on delete restrict;

comment on column public.season_players.current_save_file_id is
  'Season-scoped current save. Replaces settings.current_save:* in V2.';

create table public.team_locks (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null,
  matchday_id uuid not null,
  trainer_id uuid not null,
  season_player_id uuid not null,
  save_file_id uuid not null,
  save_sha256 text not null,
  locked_at timestamptz not null default now(),
  deadline_at timestamptz,
  is_late boolean not null default false,
  public_team_snapshot jsonb not null,
  private_team_snapshot jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint team_locks_save_sha256_chk
    check (save_sha256 ~ '^[a-f0-9]{64}$'),
  constraint team_locks_deadline_chk
    check (deadline_at is null or locked_at <= deadline_at or is_late = true),
  constraint uq_team_locks_matchday_trainer
    unique (matchday_id, trainer_id),
  constraint fk_team_locks_matchday_same_season
    foreign key (matchday_id, season_id)
    references public.matchdays(id, season_id)
    on delete restrict,
  constraint fk_team_locks_player_same_owner
    foreign key (season_player_id, season_id, trainer_id)
    references public.season_players(id, season_id, trainer_id)
    on delete restrict,
  constraint fk_team_locks_save_same_owner
    foreign key (save_file_id, season_id, trainer_id)
    references public.save_files(id, season_id, trainer_id)
    on delete restrict
);

create trigger team_locks_set_updated_at
before update on public.team_locks
for each row execute function public.set_updated_at();

comment on table public.team_locks is
  'Historical locked teams. Public snapshot is used for previews; private snapshot is owner/admin/server-only.';

commit;
-- ============================================================================
-- END 005_saves.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 006_activity_hall.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 006_activity_hall: append-only activity, Hall of Fame and archive snapshots.

begin;

create table public.activity_events (
  id uuid primary key default gen_random_uuid(),
  season_id uuid references public.seasons(id) on delete restrict,
  type text not null,
  actor_trainer_id uuid references public.trainers(id) on delete set null,
  trainer_id uuid references public.trainers(id) on delete set null,
  visibility text not null default 'public',
  dedupe_key text,
  context jsonb not null default '{}'::jsonb,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint activity_events_type_chk
    check (type = upper(type) and type ~ '^[A-Z0-9_]+$'),
  constraint activity_events_visibility_chk
    check (visibility in ('public', 'owner', 'admin', 'server_only'))
);

comment on table public.activity_events is
  'Append-only product facts. Notification views are derived and not stored.';

create table public.hall_of_fame_entries (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  competition_type text not null,
  champion_trainer_id uuid not null references public.trainers(id) on delete restrict,
  finalist_trainer_id uuid references public.trainers(id) on delete restrict,
  finalized_at timestamptz not null default now(),
  team_snapshot jsonb not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint hall_of_fame_entries_competition_type_chk
    check (competition_type in ('league', 'cup', 'tournament', 'doubles_cup')),
  constraint uq_hall_of_fame_season_competition
    unique (season_id, competition_type)
);

comment on table public.hall_of_fame_entries is
  'Immutable winner records. Champion team comes from a frozen snapshot, never from mutable current save.';

create table public.season_archive_snapshots (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null unique references public.seasons(id) on delete restrict,
  snapshot_schema_version integer not null default 1,
  snapshot jsonb not null,
  created_by_trainer_id uuid references public.trainers(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint season_archive_snapshots_schema_version_chk
    check (snapshot_schema_version > 0)
);

comment on table public.season_archive_snapshots is
  'Optional final audit/export document. Relational season data remains authoritative and is not duplicated here.';

commit;
-- ============================================================================
-- END 006_activity_hall.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 007_competitions.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 007_competitions: generic cup tables, trials/cases and penalties.

begin;

create table public.cups (
  id uuid primary key default gen_random_uuid(),
  season_id uuid references public.seasons(id) on delete restrict,
  name text not null,
  competition_type text not null default 'cup',
  format text not null,
  status text not null default 'draft',
  started_at timestamptz,
  finished_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cups_name_chk
    check (length(btrim(name)) > 0),
  constraint cups_competition_type_chk
    check (competition_type in ('cup', 'tournament', 'doubles_cup')),
  constraint cups_format_chk
    check (format in ('swiss', 'elimination', 'doubles', 'manual')),
  constraint cups_status_chk
    check (status in ('draft', 'active', 'finished', 'archived', 'discarded'))
);

create trigger cups_set_updated_at
before update on public.cups
for each row execute function public.set_updated_at();

comment on table public.cups is
  'Generic cup/tournament container. Swiss, elimination and doubles share one model through format.';

create table public.cup_participants (
  id uuid primary key default gen_random_uuid(),
  cup_id uuid not null references public.cups(id) on delete restrict,
  trainer_id uuid references public.trainers(id) on delete restrict,
  display_name text not null,
  seed_order integer,
  status text not null default 'active',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint cup_participants_display_name_chk
    check (length(btrim(display_name)) > 0),
  constraint cup_participants_seed_order_chk
    check (seed_order is null or seed_order > 0),
  constraint cup_participants_status_chk
    check (status in ('active', 'eliminated', 'dropped', 'disqualified'))
);

comment on table public.cup_participants is
  'Cup sides. For doubles/team cups, trainer_id can be null and metadata can carry member ids until product needs a richer team model.';

create table public.cup_matches (
  id uuid primary key default gen_random_uuid(),
  cup_id uuid not null references public.cups(id) on delete restrict,
  round_number integer not null,
  bracket_position integer,
  participant_a_id uuid references public.cup_participants(id) on delete restrict,
  participant_b_id uuid references public.cup_participants(id) on delete restrict,
  winner_participant_id uuid references public.cup_participants(id) on delete restrict,
  status text not null default 'scheduled',
  score text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint cup_matches_round_number_chk
    check (round_number > 0),
  constraint cup_matches_bracket_position_chk
    check (bracket_position is null or bracket_position > 0),
  constraint cup_matches_status_chk
    check (status in ('scheduled', 'completed', 'forfeit', 'bye', 'void')),
  constraint cup_matches_winner_is_side_chk
    check (
      winner_participant_id is null
      or winner_participant_id = participant_a_id
      or winner_participant_id = participant_b_id
    )
);

create trigger cup_matches_set_updated_at
before update on public.cup_matches
for each row execute function public.set_updated_at();

create table public.cup_standings (
  id uuid primary key default gen_random_uuid(),
  cup_id uuid not null references public.cups(id) on delete restrict,
  participant_id uuid not null references public.cup_participants(id) on delete restrict,
  position integer,
  points numeric(6, 2) not null default 0,
  wins integer not null default 0,
  losses integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint cup_standings_position_chk
    check (position is null or position > 0),
  constraint cup_standings_record_chk
    check (wins >= 0 and losses >= 0),
  constraint uq_cup_standings_participant
    unique (cup_id, participant_id)
);

create trigger cup_standings_set_updated_at
before update on public.cup_standings
for each row execute function public.set_updated_at();

create table public.trial_cases (
  id uuid primary key default gen_random_uuid(),
  season_id uuid references public.seasons(id) on delete restrict,
  matchday_id uuid,
  accused_trainer_id uuid references public.trainers(id) on delete restrict,
  created_by_trainer_id uuid references public.trainers(id) on delete set null,
  title text not null,
  description text not null default '',
  status text not null default 'open',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint trial_cases_title_chk
    check (length(btrim(title)) > 0),
  constraint trial_cases_status_chk
    check (status in ('open', 'resolved', 'dismissed', 'cancelled')),
  constraint trial_cases_matchday_requires_season_chk
    check (matchday_id is null or season_id is not null),
  constraint fk_trial_cases_matchday_same_season
    foreign key (matchday_id, season_id)
    references public.matchdays(id, season_id)
    on delete restrict
);

create trigger trial_cases_set_updated_at
before update on public.trial_cases
for each row execute function public.set_updated_at();

create table public.trial_votes (
  id uuid primary key default gen_random_uuid(),
  trial_case_id uuid not null references public.trial_cases(id) on delete restrict,
  voter_trainer_id uuid not null references public.trainers(id) on delete restrict,
  vote text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint trial_votes_vote_chk
    check (vote in ('guilty', 'not_guilty', 'abstain', 'other')),
  constraint uq_trial_votes_case_voter
    unique (trial_case_id, voter_trainer_id)
);

create table public.penalties (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.seasons(id) on delete restrict,
  trainer_id uuid not null references public.trainers(id) on delete restrict,
  matchday_id uuid,
  trial_case_id uuid references public.trial_cases(id) on delete restrict,
  penalty_type text not null,
  amount integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  created_by_trainer_id uuid references public.trainers(id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  constraint penalties_type_chk
    check (length(btrim(penalty_type)) > 0),
  constraint fk_penalties_matchday_same_season
    foreign key (matchday_id, season_id)
    references public.matchdays(id, season_id)
    on delete restrict
);

comment on table public.penalties is
  'Official penalties from trials/admin. Effects can be matchday-scoped and are reflected in snapshots/ledger by application logic.';

commit;
-- ============================================================================
-- END 007_competitions.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 008_indexes.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 008_indexes: query indexes and uniqueness that depends on partial predicates.

begin;

create unique index uq_seasons_one_active
  on public.seasons ((status))
  where status = 'active';

create index idx_trainers_slug_enabled
  on public.trainers (slug)
  where globally_enabled = true;

create index idx_season_players_season_status
  on public.season_players (season_id, status, seed_order);

create index idx_season_config_versions_season_effective_desc
  on public.season_config_versions (season_id, effective_from_matchday desc);

create index idx_division_memberships_player_range
  on public.division_memberships (season_player_id, effective_from_matchday_number, effective_to_matchday_number);

create index idx_trainer_flags_season_type
  on public.trainer_flags (season_id, flag_type, trainer_id);

create index idx_pokemon_flags_owner_type
  on public.pokemon_flags (season_id, trainer_id, flag_type);

create index idx_matchdays_season_status
  on public.matchdays (season_id, status, number);

create index idx_matches_matchday_division
  on public.matches (matchday_id, division_id, status);

create index idx_matchday_movements_matchday
  on public.matchday_movements (matchday_id, movement_type);

create index idx_shop_items_category_enabled
  on public.shop_items (category, enabled, code);

create index idx_shop_promotions_season_matchday_status
  on public.shop_promotions (season_id, matchday_id, status, activates_at);

create unique index uq_shop_promotions_dedupe_key
  on public.shop_promotions (dedupe_key)
  where dedupe_key is not null and dedupe_key <> '';

create index idx_purchases_trainer_recent
  on public.purchases (trainer_id, purchased_at desc);

create index idx_purchases_season_item_status
  on public.purchases (season_id, shop_item_id, status);

create index idx_purchases_promotion
  on public.purchases (promotion_id)
  where promotion_id is not null;

create index idx_redemptions_purchase
  on public.redemptions (purchase_id, redeemed_at desc);

create index idx_coin_transactions_trainer
  on public.coin_transactions (season_id, trainer_id, created_at desc);

create index idx_save_files_trainer_recent
  on public.save_files (season_id, trainer_id, uploaded_at desc);

create index idx_save_files_sha256
  on public.save_files (sha256);

create index idx_parsed_saves_file_recent
  on public.parsed_saves (save_file_id, parsed_at desc);

create index idx_team_locks_matchday
  on public.team_locks (matchday_id, trainer_id);

create index idx_activity_events_recent
  on public.activity_events (created_at desc);

create index idx_activity_events_season_recent
  on public.activity_events (season_id, created_at desc);

create unique index uq_activity_events_dedupe_key
  on public.activity_events (dedupe_key)
  where dedupe_key is not null and dedupe_key <> '';

create index idx_hall_of_fame_champion
  on public.hall_of_fame_entries (champion_trainer_id, finalized_at desc);

create index idx_cups_season_status
  on public.cups (season_id, status, created_at desc);

create index idx_cup_matches_round
  on public.cup_matches (cup_id, round_number, bracket_position);

create index idx_trial_cases_season_status
  on public.trial_cases (season_id, status, created_at desc);

create index idx_penalties_trainer
  on public.penalties (season_id, trainer_id, created_at desc);

comment on index public.uq_seasons_one_active is
  'PokeApp runs one active league season at a time.';

commit;
-- ============================================================================
-- END 008_indexes.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 009_seed.sql
-- ============================================================================
-- PokeApp Supabase V2 greenfield schema.
-- 009_seed: minimal reproducible seed for bootstrap/staging.
-- No credentials or historical results are seeded here.

begin;

insert into public.app_settings (key, value, description)
values
  ('schema.version', '"2.0-greenfield"'::jsonb, 'Supabase V2 schema marker.'),
  ('storage.raw_saves_bucket', '"raw-saves"'::jsonb, 'Private bucket expected for raw save files.')
on conflict (key) do update
set value = excluded.value,
    description = excluded.description,
    updated_at = now();

insert into public.trainers (display_name, slug, metadata)
values
  ('Anto', 'anto', '{"seeded": true}'::jsonb),
  ('Victor', 'victor', '{"seeded": true}'::jsonb),
  ('Rober', 'rober', '{"seeded": true}'::jsonb),
  ('Samu', 'samu', '{"seeded": true}'::jsonb),
  ('Daviry', 'daviry', '{"seeded": true}'::jsonb),
  ('Sergio', 'sergio', '{"seeded": true}'::jsonb),
  ('Iker', 'iker', '{"seeded": true}'::jsonb),
  ('Aaron', 'aaron', '{"seeded": true}'::jsonb),
  ('Miguel', 'miguel', '{"seeded": true}'::jsonb),
  ('Barto', 'barto', '{"seeded": true}'::jsonb)
on conflict (slug) do update
set display_name = excluded.display_name,
    globally_enabled = true,
    updated_at = now();

insert into public.shop_items (code, name, category, description, base_price, image_key, metadata)
values
  ('revivir_pokemon', 'Revivir Pokemon', 'comodines', 'Permite revivir un Pokemon segun las reglas activas.', 12, 'max-revive', '{"seeded": true}'::jsonb),
  ('robar_pokemon', 'Robar Pokemon', 'comodines', 'Permite robar un Pokemon segun las reglas activas.', 12, 'dread-plate', '{"seeded": true}'::jsonb),
  ('captura_extra', 'Captura Extra', 'comodines', 'Permite una captura adicional segun las reglas activas.', 5, 'ultra-ball', '{"seeded": true}'::jsonb),
  ('blindar_pokemon', 'Blindar Pokemon', 'comodines', 'Protege un Pokemon frente a robo segun las reglas activas.', 12, 'metal-coat', '{"seeded": true}'::jsonb),
  ('fosil', 'Fosil', 'comodines', 'Permite usar un fosil segun las reglas activas.', 5, 'helix-fossil', '{"seeded": true}'::jsonb),

  ('baya_aranja', 'Baya Aranja', 'bayas', 'Restaura 10 PS al 50% PS.', 2, 'oran-berry', '{"seeded": true}'::jsonb),
  ('baya_zidra', 'Baya Zidra', 'bayas', 'Restaura 25% de PS maximos.', 3, 'sitrus-berry', '{"seeded": true}'::jsonb),
  ('baya_zreza', 'Baya Zreza', 'bayas', 'Cura paralisis.', 2, 'cheri-berry', '{"seeded": true}'::jsonb),
  ('baya_ziuela', 'Baya Ziuela', 'bayas', 'Cura sueno.', 3, 'chesto-berry', '{"seeded": true}'::jsonb),
  ('baya_meloc', 'Baya Meloc', 'bayas', 'Cura envenenamiento.', 2, 'pecha-berry', '{"seeded": true}'::jsonb),
  ('baya_safre', 'Baya Safre', 'bayas', 'Cura quemaduras.', 2, 'rawst-berry', '{"seeded": true}'::jsonb),
  ('baya_perasi', 'Baya Perasi', 'bayas', 'Cura congelacion.', 2, 'aspear-berry', '{"seeded": true}'::jsonb),
  ('baya_atania', 'Baya Atania', 'bayas', 'Cura confusion.', 2, 'persim-berry', '{"seeded": true}'::jsonb),
  ('baya_aslac', 'Baya Aslac', 'bayas', 'Velocidad +1 etapa al 25% PS.', 2, 'salac-berry', '{"seeded": true}'::jsonb),
  ('baya_lichi', 'Baya Lichi', 'bayas', 'Ataque +1 etapa al 25% PS.', 2, 'liechi-berry', '{"seeded": true}'::jsonb),
  ('baya_petaya', 'Baya Petaya', 'bayas', 'At. Esp. +1 etapa al 25% PS.', 2, 'petaya-berry', '{"seeded": true}'::jsonb),
  ('baya_ganlon', 'Baya Ganlon', 'bayas', 'Defensa +1 etapa al 25% PS.', 2, 'ganlon-berry', '{"seeded": true}'::jsonb),
  ('baya_apicot', 'Baya Apicot', 'bayas', 'Def. Esp. +1 etapa al 25% PS.', 2, 'apicot-berry', '{"seeded": true}'::jsonb),
  ('baya_lansat', 'Baya Lansat', 'bayas', 'Ratio critico +2 etapas al 25% PS.', 2, 'lansat-berry', '{"seeded": true}'::jsonb),
  ('baya_starf', 'Baya Starf', 'bayas', 'Sube mucho una stat al azar.', 2, 'starf-berry', '{"seeded": true}'::jsonb),
  ('baya_occa', 'Baya Occa (Fuego)', 'bayas', 'Reduce dano de Fuego supereficaz un 50%.', 3, 'occa-berry', '{"seeded": true}'::jsonb),
  ('baya_passho', 'Baya Passho (Agua)', 'bayas', 'Reduce dano de Agua supereficaz un 50%.', 3, 'passho-berry', '{"seeded": true}'::jsonb),
  ('baya_wacan', 'Baya Wacan (Electrico)', 'bayas', 'Reduce dano de Electrico supereficaz un 50%.', 3, 'wacan-berry', '{"seeded": true}'::jsonb),
  ('baya_rindo', 'Baya Rindo (Planta)', 'bayas', 'Reduce dano de Planta supereficaz un 50%.', 3, 'rindo-berry', '{"seeded": true}'::jsonb),
  ('baya_yache', 'Baya Yache (Hielo)', 'bayas', 'Reduce dano de Hielo supereficaz un 50%.', 3, 'yache-berry', '{"seeded": true}'::jsonb),
  ('baya_shuca', 'Baya Shuca (Tierra)', 'bayas', 'Reduce dano de Tierra supereficaz un 50%.', 3, 'shuca-berry', '{"seeded": true}'::jsonb),
  ('baya_chople', 'Baya Chople (Lucha)', 'bayas', 'Reduce dano de Lucha supereficaz un 50%.', 3, 'chople-berry', '{"seeded": true}'::jsonb),
  ('baya_kebia', 'Baya Kebia (Veneno)', 'bayas', 'Reduce dano de Veneno supereficaz un 50%.', 3, 'kebia-berry', '{"seeded": true}'::jsonb),
  ('baya_coba', 'Baya Coba (Volador)', 'bayas', 'Reduce dano de Volador supereficaz un 50%.', 3, 'coba-berry', '{"seeded": true}'::jsonb),
  ('baya_payapa', 'Baya Payapa (Psiquico)', 'bayas', 'Reduce dano de Psiquico supereficaz un 50%.', 3, 'payapa-berry', '{"seeded": true}'::jsonb),
  ('baya_tanga', 'Baya Tanga (Bicho)', 'bayas', 'Reduce dano de Bicho supereficaz un 50%.', 3, 'tanga-berry', '{"seeded": true}'::jsonb),
  ('baya_charti', 'Baya Charti (Roca)', 'bayas', 'Reduce dano de Roca supereficaz un 50%.', 3, 'charti-berry', '{"seeded": true}'::jsonb),
  ('baya_kasib', 'Baya Kasib (Fantasma)', 'bayas', 'Reduce dano de Fantasma supereficaz un 50%.', 3, 'kasib-berry', '{"seeded": true}'::jsonb),
  ('baya_haban', 'Baya Haban (Dragon)', 'bayas', 'Reduce dano de Dragon supereficaz un 50%.', 3, 'haban-berry', '{"seeded": true}'::jsonb),
  ('baya_colbur', 'Baya Colbur (Siniestro)', 'bayas', 'Reduce dano de Siniestro supereficaz un 50%.', 3, 'colbur-berry', '{"seeded": true}'::jsonb),
  ('baya_babiri', 'Baya Babiri (Acero)', 'bayas', 'Reduce dano de Acero supereficaz un 50%.', 3, 'babiri-berry', '{"seeded": true}'::jsonb),
  ('baya_chilan', 'Baya Chilan (Normal)', 'bayas', 'Reduce dano de Normal un 50%.', 3, 'chilan-berry', '{"seeded": true}'::jsonb),

  ('gafas_elegidas', 'Gafas Elegidas', 'competitivos', 'At. Esp. +50%; bloquea cambio de movimiento.', 8, 'choice-specs', '{"seeded": true}'::jsonb),
  ('cinta_elegida', 'Cinta Elegida', 'competitivos', 'Ataque +50%; bloquea cambio de movimiento.', 8, 'choice-band', '{"seeded": true}'::jsonb),
  ('panuelo_elegido', 'Panuelo Elegido', 'competitivos', 'Velocidad +50%; bloquea cambio de movimiento.', 8, 'choice-scarf', '{"seeded": true}'::jsonb),
  ('restos', 'Restos', 'competitivos', 'Restaura 1/16 de PS por turno.', 8, 'leftovers', '{"seeded": true}'::jsonb),
  ('banda_focus', 'Banda Focus', 'competitivos', 'Con PS completos, sobrevive a 1 golpe con 1 PS.', 7, 'focus-sash', '{"seeded": true}'::jsonb),
  ('vidasfera', 'Vidasfera', 'competitivos', 'Dano +30%; pierde 10% PS max tras atacar.', 7, 'life-orb', '{"seeded": true}'::jsonb),
  ('mineral_evolutivo', 'Mineral Evolutivo', 'competitivos', 'Defensa y Def. Esp. +50% si el Pokemon aun puede evolucionar.', 8, 'eviolite', '{"seeded": true}'::jsonb),
  ('casco_dentado', 'Casco Dentado', 'competitivos', 'Hace dano al rival si golpea con contacto.', 7, 'rocky-helmet', '{"seeded": true}'::jsonb),
  ('globo_helio', 'Globo Helio', 'competitivos', 'Inmunidad a Tierra hasta recibir dano.', 5, 'air-balloon', '{"seeded": true}'::jsonb),
  ('gemas_elementales', 'Gemas Elementales', 'competitivos', 'Potencian una vez un movimiento del tipo de la gema.', 6, 'fire-gem', '{"seeded": true}'::jsonb),
  ('boton_escape', 'Boton Escape', 'competitivos', 'Cambia al portador tras recibir dano.', 4, 'eject-button', '{"seeded": true}'::jsonb),
  ('tarjeta_roja', 'Tarjeta Roja', 'competitivos', 'Expulsa al atacante y fuerza cambio.', 4, 'red-card', '{"seeded": true}'::jsonb),
  ('hierba_blanca', 'Hierba Blanca', 'competitivos', 'Restaura reducciones de estadisticas.', 5, 'white-herb', '{"seeded": true}'::jsonb),
  ('roca_del_rey', 'Roca del Rey', 'competitivos', 'Puede hacer retroceder al golpear.', 5, 'kings-rock', '{"seeded": true}'::jsonb),
  ('periscopio', 'Periscopio', 'competitivos', 'Sube el ratio critico.', 5, 'scope-lens', '{"seeded": true}'::jsonb),
  ('lupa', 'Lupa', 'competitivos', 'Precision +20% si el usuario actua despues.', 5, 'zoom-lens', '{"seeded": true}'::jsonb),
  ('toxisfera', 'Toxisfera', 'competitivos', 'Envenena gravemente al portador al final del turno.', 5, 'toxic-orb', '{"seeded": true}'::jsonb),
  ('llamasfera', 'Llamasfera', 'competitivos', 'Quema al portador al final del turno.', 5, 'flame-orb', '{"seeded": true}'::jsonb),
  ('objeto_potenciador_tipo', 'Objeto Potenciador de Tipo', 'competitivos', 'Potencia movimientos de un tipo.', 4, 'silk-scarf', '{"seeded": true}'::jsonb),

  ('capsula_habilidad', 'Capsula Habilidad', 'crianza', 'Cambia habilidad normal.', 8, 'ability-capsule', '{"seeded": true}'::jsonb),
  ('chapa_dorada', 'Chapa Dorada', 'crianza', 'Maximiza IVs en todos los stats.', 15, 'gold-bottle-cap', '{"seeded": true, "promotion_blocked": true}'::jsonb),
  ('chapa_plateada', 'Chapa Plateada', 'crianza', 'Maximiza un IV concreto.', 6, 'bottle-cap', '{"seeded": true}'::jsonb),
  ('menta_naturaleza', 'Menta de Naturaleza', 'crianza', 'Cambia naturaleza.', 6, 'leaf-stone', '{"seeded": true}'::jsonb),
  ('objeto_evolutivo', 'Objeto Evolutivo', 'crianza', 'Piedras y otros objetos de evolucion.', 4, 'dawn-stone', '{"seeded": true}'::jsonb)
on conflict (code) do update
set name = excluded.name,
    category = excluded.category,
    description = excluded.description,
    base_price = excluded.base_price,
    image_key = excluded.image_key,
    metadata = excluded.metadata,
    enabled = true,
    updated_at = now();

-- Supabase-only bucket bootstrap. Plain Postgres builds skip this safely.
do $$
begin
  if exists (
    select 1
    from information_schema.schemata
    where schema_name = 'storage'
  ) then
    execute $storage$
      insert into storage.buckets (id, name, public)
      values ('raw-saves', 'raw-saves', false)
      on conflict (id) do update
      set name = excluded.name,
          public = false
    $storage$;
  end if;
end;
$$;

commit;
-- ============================================================================
-- END 009_seed.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 010_security_helpers.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 010_security_helpers: auth identity, admin flag and safe RLS helpers.

begin;

alter table public.trainers
  add column is_admin boolean not null default false;

comment on column public.trainers.is_admin is
  'Explicit administrative identity for V2 RLS. Do not infer admin from display_name or slug.';

create or replace function public.current_auth_uid()
returns uuid
language plpgsql
stable
set search_path = ''
as $$
declare
  auth_uid uuid;
  raw_sub text;
begin
  begin
    execute 'select auth.uid()' into auth_uid;
  exception
    when invalid_schema_name or undefined_function then
      auth_uid := null;
  end;

  if auth_uid is not null then
    return auth_uid;
  end if;

  raw_sub := nullif(pg_catalog.current_setting('request.jwt.claim.sub', true), '');
  if raw_sub is null then
    return null;
  end if;

  begin
    return raw_sub::uuid;
  exception
    when invalid_text_representation then
      return null;
  end;
end;
$$;

comment on function public.current_auth_uid() is
  'Returns Supabase auth.uid(). Plain PostgreSQL validation falls back to request.jwt.claim.sub.';

create or replace function public.current_trainer_id()
returns uuid
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  select t.id
  from public.trainers as t
  where t.auth_user_id = public.current_auth_uid()
    and t.globally_enabled = true
  limit 1
$$;

comment on function public.current_trainer_id() is
  'Resolves the authenticated Supabase user to the enabled PokeApp trainer id.';

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  select coalesce(
    (
      select true
      from public.trainers as t
      where t.auth_user_id = public.current_auth_uid()
        and t.globally_enabled = true
        and t.is_admin = true
      limit 1
    ),
    false
  )
$$;

comment on function public.is_current_user_admin() is
  'Checks the explicit trainers.is_admin flag for the authenticated user.';

create or replace function public.current_user_owns_trainer(p_trainer_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  select p_trainer_id is not null
    and p_trainer_id = public.current_trainer_id()
$$;

comment on function public.current_user_owns_trainer(uuid) is
  'Small policy helper for trainer-owned rows.';

revoke all on function public.current_auth_uid() from public;
revoke all on function public.current_trainer_id() from public;
revoke all on function public.is_current_user_admin() from public;
revoke all on function public.current_user_owns_trainer(uuid) from public;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on function public.current_auth_uid() from anon;
    revoke all on function public.current_trainer_id() from anon;
    revoke all on function public.is_current_user_admin() from anon;
    revoke all on function public.current_user_owns_trainer(uuid) from anon;
  end if;
end;
$$;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    grant execute on function public.current_auth_uid() to authenticated;
    grant execute on function public.current_trainer_id() to authenticated;
    grant execute on function public.is_current_user_admin() to authenticated;
    grant execute on function public.current_user_owns_trainer(uuid) to authenticated;
  end if;

  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant execute on function public.current_auth_uid() to service_role;
    grant execute on function public.current_trainer_id() to service_role;
    grant execute on function public.is_current_user_admin() to service_role;
    grant execute on function public.current_user_owns_trainer(uuid) to service_role;
  end if;
end;
$$;

commit;
-- ============================================================================
-- END 010_security_helpers.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 011_rls_policies.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 011_rls_policies: default-deny RLS on application tables.

begin;

do $$
declare
  table_name text;
  table_names text[] := array[
    'activity_events',
    'app_settings',
    'coin_transactions',
    'cup_matches',
    'cup_participants',
    'cup_standings',
    'cups',
    'division_memberships',
    'divisions',
    'hall_of_fame_entries',
    'matchday_movements',
    'matchday_snapshots',
    'matchdays',
    'matches',
    'parsed_saves',
    'penalties',
    'pokemon_flags',
    'purchases',
    'redemptions',
    'save_files',
    'season_archive_snapshots',
    'season_config_versions',
    'season_player_stats',
    'season_players',
    'seasons',
    'shop_items',
    'shop_promotions',
    'team_locks',
    'trainer_flags',
    'trainers',
    'trial_cases',
    'trial_votes'
  ];
begin
  foreach table_name in array table_names loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from public', table_name);

    if exists (select 1 from pg_roles where rolname = 'anon') then
      execute format('revoke all on table public.%I from anon', table_name);
    end if;

    if exists (select 1 from pg_roles where rolname = 'authenticated') then
      execute format(
        'grant select, insert, update, delete on table public.%I to authenticated',
        table_name
      );
    end if;

    if exists (select 1 from pg_roles where rolname = 'service_role') then
      execute format('grant all privileges on table public.%I to service_role', table_name);
    end if;
  end loop;

  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    grant usage on schema public to authenticated;
  end if;

  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant usage on schema public to service_role;
  end if;
end;
$$;

create policy app_settings_admin_read
on public.app_settings
for select
using (public.is_current_user_admin());

create policy app_settings_admin_insert
on public.app_settings
for insert
with check (public.is_current_user_admin());

create policy app_settings_admin_update
on public.app_settings
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy trainers_self_admin_read
on public.trainers
for select
using (id = public.current_trainer_id() or public.is_current_user_admin());

create policy trainers_admin_insert
on public.trainers
for insert
with check (public.is_current_user_admin());

create policy trainers_admin_update
on public.trainers
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy seasons_admin_read
on public.seasons
for select
using (public.is_current_user_admin());

create policy seasons_admin_insert
on public.seasons
for insert
with check (public.is_current_user_admin());

create policy seasons_admin_update
on public.seasons
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy season_players_owner_admin_read
on public.season_players
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy season_players_admin_insert
on public.season_players
for insert
with check (public.is_current_user_admin());

create policy season_players_admin_update
on public.season_players
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy season_player_stats_owner_admin_read
on public.season_player_stats
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy season_player_stats_admin_insert
on public.season_player_stats
for insert
with check (public.is_current_user_admin());

create policy season_player_stats_admin_update
on public.season_player_stats
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy trainer_flags_owner_admin_read
on public.trainer_flags
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy trainer_flags_admin_insert
on public.trainer_flags
for insert
with check (public.is_current_user_admin());

create policy trainer_flags_admin_update
on public.trainer_flags
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy pokemon_flags_owner_admin_read
on public.pokemon_flags
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy pokemon_flags_admin_insert
on public.pokemon_flags
for insert
with check (public.is_current_user_admin());

create policy pokemon_flags_admin_update
on public.pokemon_flags
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy season_config_versions_admin_read
on public.season_config_versions
for select
using (public.is_current_user_admin());

create policy season_config_versions_admin_insert
on public.season_config_versions
for insert
with check (public.is_current_user_admin());

create policy season_config_versions_admin_update
on public.season_config_versions
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy divisions_admin_read
on public.divisions
for select
using (public.is_current_user_admin());

create policy divisions_admin_insert
on public.divisions
for insert
with check (public.is_current_user_admin());

create policy divisions_admin_update
on public.divisions
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy division_memberships_admin_read
on public.division_memberships
for select
using (public.is_current_user_admin());

create policy division_memberships_admin_insert
on public.division_memberships
for insert
with check (public.is_current_user_admin());

create policy division_memberships_admin_update
on public.division_memberships
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy matchdays_admin_read
on public.matchdays
for select
using (public.is_current_user_admin());

create policy matchdays_admin_insert
on public.matchdays
for insert
with check (public.is_current_user_admin());

create policy matchdays_admin_update
on public.matchdays
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy matches_admin_read
on public.matches
for select
using (public.is_current_user_admin());

create policy matches_admin_insert
on public.matches
for insert
with check (public.is_current_user_admin());

create policy matches_admin_update
on public.matches
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy matchday_snapshots_admin_read
on public.matchday_snapshots
for select
using (public.is_current_user_admin());

create policy matchday_snapshots_admin_insert
on public.matchday_snapshots
for insert
with check (public.is_current_user_admin());

create policy matchday_snapshots_admin_update
on public.matchday_snapshots
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy matchday_movements_admin_read
on public.matchday_movements
for select
using (public.is_current_user_admin());

create policy matchday_movements_admin_insert
on public.matchday_movements
for insert
with check (public.is_current_user_admin());

create policy matchday_movements_admin_update
on public.matchday_movements
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy shop_items_admin_read
on public.shop_items
for select
using (public.is_current_user_admin());

create policy shop_items_admin_insert
on public.shop_items
for insert
with check (public.is_current_user_admin());

create policy shop_items_admin_update
on public.shop_items
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy shop_promotions_admin_read
on public.shop_promotions
for select
using (public.is_current_user_admin());

create policy shop_promotions_admin_insert
on public.shop_promotions
for insert
with check (public.is_current_user_admin());

create policy shop_promotions_admin_update
on public.shop_promotions
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy purchases_owner_admin_read
on public.purchases
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy redemptions_owner_admin_read
on public.redemptions
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy coin_transactions_owner_admin_read
on public.coin_transactions
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy save_files_owner_admin_read
on public.save_files
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy parsed_saves_owner_admin_read
on public.parsed_saves
for select
using (
  public.is_current_user_admin()
  or exists (
    select 1
    from public.save_files as sf
    where sf.id = parsed_saves.save_file_id
      and sf.trainer_id = public.current_trainer_id()
  )
);

create policy team_locks_owner_admin_read
on public.team_locks
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy activity_events_visibility_read
on public.activity_events
for select
using (
  visibility = 'public'
  or public.is_current_user_admin()
  or (
    visibility = 'owner'
    and trainer_id = public.current_trainer_id()
  )
);

create policy hall_of_fame_entries_admin_read
on public.hall_of_fame_entries
for select
using (public.is_current_user_admin());

create policy hall_of_fame_entries_admin_insert
on public.hall_of_fame_entries
for insert
with check (public.is_current_user_admin());

create policy hall_of_fame_entries_admin_update
on public.hall_of_fame_entries
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy season_archive_snapshots_admin_read
on public.season_archive_snapshots
for select
using (public.is_current_user_admin());

create policy season_archive_snapshots_admin_insert
on public.season_archive_snapshots
for insert
with check (public.is_current_user_admin());

create policy season_archive_snapshots_admin_update
on public.season_archive_snapshots
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy cups_admin_read
on public.cups
for select
using (public.is_current_user_admin());

create policy cups_admin_insert
on public.cups
for insert
with check (public.is_current_user_admin());

create policy cups_admin_update
on public.cups
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy cup_participants_admin_read
on public.cup_participants
for select
using (public.is_current_user_admin());

create policy cup_participants_admin_insert
on public.cup_participants
for insert
with check (public.is_current_user_admin());

create policy cup_participants_admin_update
on public.cup_participants
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy cup_matches_admin_read
on public.cup_matches
for select
using (public.is_current_user_admin());

create policy cup_matches_admin_insert
on public.cup_matches
for insert
with check (public.is_current_user_admin());

create policy cup_matches_admin_update
on public.cup_matches
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy cup_standings_admin_read
on public.cup_standings
for select
using (public.is_current_user_admin());

create policy cup_standings_admin_insert
on public.cup_standings
for insert
with check (public.is_current_user_admin());

create policy cup_standings_admin_update
on public.cup_standings
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

create policy trial_cases_owner_admin_read
on public.trial_cases
for select
using (
  public.is_current_user_admin()
  or created_by_trainer_id = public.current_trainer_id()
  or accused_trainer_id = public.current_trainer_id()
);

create policy trial_cases_owner_insert
on public.trial_cases
for insert
with check (created_by_trainer_id = public.current_trainer_id());

create policy trial_cases_owner_update
on public.trial_cases
for update
using (
  public.is_current_user_admin()
  or created_by_trainer_id = public.current_trainer_id()
)
with check (
  public.is_current_user_admin()
  or created_by_trainer_id = public.current_trainer_id()
);

create policy trial_votes_voter_admin_read
on public.trial_votes
for select
using (voter_trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy trial_votes_voter_insert
on public.trial_votes
for insert
with check (voter_trainer_id = public.current_trainer_id());

create policy trial_votes_voter_update
on public.trial_votes
for update
using (voter_trainer_id = public.current_trainer_id() or public.is_current_user_admin())
with check (voter_trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy penalties_owner_admin_read
on public.penalties
for select
using (trainer_id = public.current_trainer_id() or public.is_current_user_admin());

create policy penalties_admin_insert
on public.penalties
for insert
with check (public.is_current_user_admin());

create policy penalties_admin_update
on public.penalties
for update
using (public.is_current_user_admin())
with check (public.is_current_user_admin());

commit;
-- ============================================================================
-- END 011_rls_policies.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 012_security_views.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 012_security_views: safe read projections for authenticated clients.

begin;

create or replace view public.public_trainers
with (security_invoker = true, security_barrier = true)
as
select
  id,
  display_name,
  slug,
  globally_enabled,
  created_at,
  updated_at
from public.trainers
where globally_enabled = true;

create or replace view public.current_trainer_profile
with (security_invoker = true, security_barrier = true)
as
select
  id,
  display_name,
  slug,
  auth_user_id,
  globally_enabled,
  is_admin,
  metadata,
  created_at,
  updated_at
from public.trainers
where id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.public_seasons
with (security_invoker = true, security_barrier = true)
as
select
  id,
  name,
  status,
  started_at,
  finished_at,
  archived_at,
  discarded_at,
  created_at,
  updated_at
from public.seasons
where status <> 'discarded';

create or replace view public.public_season_players
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  trainer_id,
  status,
  seed_order,
  joined_at,
  left_at,
  created_at,
  updated_at
from public.season_players;

create or replace view public.public_season_player_stats
with (security_invoker = true, security_barrier = true)
as
select
  season_player_id,
  season_id,
  trainer_id,
  badges_count,
  updated_at
from public.season_player_stats;

create or replace view public.public_trainer_flags
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  trainer_id,
  season_player_id,
  flag_type,
  flag_value,
  created_at,
  updated_at
from public.trainer_flags
where flag_type = 'robbed'
  and flag_value = true;

create or replace view public.current_trainer_flags
with (security_invoker = true, security_barrier = true)
as
select *
from public.trainer_flags
where trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.current_pokemon_flags
with (security_invoker = true, security_barrier = true)
as
select *
from public.pokemon_flags
where trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.public_season_config_versions
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  version_number,
  name,
  effective_from_matchday,
  total_matchdays,
  division_count,
  promotion_relegation_count,
  scoring_json,
  coin_rewards_json,
  rules_json,
  locked_at,
  created_at
from public.season_config_versions;

create or replace view public.public_divisions
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  code,
  name,
  tier_order,
  created_at
from public.divisions;

create or replace view public.public_division_memberships
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  season_player_id,
  division_id,
  effective_from_matchday_number,
  effective_to_matchday_number,
  source_matchday_id,
  reason,
  created_at
from public.division_memberships;

create or replace view public.public_matchdays
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  number,
  status,
  season_config_version_id,
  opened_at,
  closed_at,
  created_at,
  updated_at
from public.matchdays;

create or replace view public.public_matches
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  matchday_id,
  division_id,
  player_a_id,
  player_b_id,
  winner_id,
  status,
  result_code,
  created_at,
  updated_at
from public.matches;

create or replace view public.public_matchday_snapshots
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  matchday_id,
  config_version_id,
  revision,
  snapshot_schema_version,
  closed_at,
  snapshot,
  created_at,
  updated_at
from public.matchday_snapshots;

create or replace view public.public_matchday_movements
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  matchday_id,
  season_player_id,
  from_division_id,
  to_division_id,
  movement_type,
  reason,
  created_at
from public.matchday_movements;

create or replace view public.public_shop_items
with (security_invoker = true, security_barrier = true)
as
select
  id,
  code,
  name,
  category,
  description,
  base_price,
  enabled,
  image_key,
  created_at,
  updated_at
from public.shop_items
where enabled = true;

create or replace view public.public_shop_promotions
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  matchday_id,
  shop_item_id,
  promotion_type,
  status,
  base_price,
  effective_price,
  stock_total,
  stock_used,
  announced_at,
  activates_at,
  ends_at,
  exhausted_at,
  created_at,
  updated_at
from public.shop_promotions
where status in ('active', 'exhausted', 'ended')
  and (activates_at is null or activates_at <= now());

create or replace view public.current_purchases
with (security_invoker = true, security_barrier = true)
as
select *
from public.purchases
where trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.current_redemptions
with (security_invoker = true, security_barrier = true)
as
select *
from public.redemptions
where trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.current_coin_transactions
with (security_invoker = true, security_barrier = true)
as
select *
from public.coin_transactions
where trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.public_coin_balances
with (security_invoker = true, security_barrier = true)
as
select
  season_id,
  trainer_id,
  coalesce(sum(amount), 0)::integer as balance
from public.coin_transactions
group by season_id, trainer_id;

create or replace view public.current_save_files
with (security_invoker = true, security_barrier = true)
as
select *
from public.save_files
where trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.current_parsed_saves
with (security_invoker = true, security_barrier = true)
as
select ps.*
from public.parsed_saves as ps
join public.save_files as sf
  on sf.id = ps.save_file_id
where sf.trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.public_team_locks
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  matchday_id,
  trainer_id,
  season_player_id,
  locked_at,
  deadline_at,
  is_late,
  public_team_snapshot,
  created_at,
  updated_at
from public.team_locks;

create or replace view public.current_team_locks
with (security_invoker = true, security_barrier = true)
as
select *
from public.team_locks
where trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.public_activity_events
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  type,
  actor_trainer_id,
  trainer_id,
  visibility,
  dedupe_key,
  context,
  payload,
  created_at
from public.activity_events
where visibility = 'public';

create or replace view public.current_activity_events
with (security_invoker = true, security_barrier = true)
as
select *
from public.activity_events
where visibility = 'public'
   or public.is_current_user_admin()
   or (
     visibility = 'owner'
     and trainer_id = public.current_trainer_id()
   );

create or replace view public.public_hall_of_fame
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  competition_type,
  champion_trainer_id,
  finalist_trainer_id,
  finalized_at,
  team_snapshot,
  created_at
from public.hall_of_fame_entries;

create or replace view public.public_cups
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  name,
  competition_type,
  format,
  status,
  started_at,
  finished_at,
  created_at,
  updated_at
from public.cups
where status <> 'discarded';

create or replace view public.public_cup_participants
with (security_invoker = true, security_barrier = true)
as
select
  id,
  cup_id,
  trainer_id,
  display_name,
  seed_order,
  status,
  created_at
from public.cup_participants;

create or replace view public.public_cup_matches
with (security_invoker = true, security_barrier = true)
as
select
  id,
  cup_id,
  round_number,
  bracket_position,
  participant_a_id,
  participant_b_id,
  winner_participant_id,
  status,
  score,
  created_at,
  updated_at
from public.cup_matches;

create or replace view public.public_cup_standings
with (security_invoker = true, security_barrier = true)
as
select
  id,
  cup_id,
  participant_id,
  position,
  points,
  wins,
  losses,
  updated_at
from public.cup_standings;

create or replace view public.public_trial_cases
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  matchday_id,
  accused_trainer_id,
  created_by_trainer_id,
  title,
  description,
  status,
  created_at,
  resolved_at,
  updated_at
from public.trial_cases
where status <> 'cancelled'
  and (
    payload ->> 'is_public' is null
    or lower(payload ->> 'is_public') not in ('false', '0', 'no')
  );

create or replace view public.current_trial_cases
with (security_invoker = true, security_barrier = true)
as
select *
from public.trial_cases
where public.is_current_user_admin()
   or created_by_trainer_id = public.current_trainer_id()
   or accused_trainer_id = public.current_trainer_id()
   or (
     payload ->> 'is_public' is null
     or lower(payload ->> 'is_public') not in ('false', '0', 'no')
   );

create or replace view public.current_trial_votes
with (security_invoker = true, security_barrier = true)
as
select *
from public.trial_votes
where voter_trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

create or replace view public.public_penalties
with (security_invoker = true, security_barrier = true)
as
select
  id,
  season_id,
  trainer_id,
  matchday_id,
  trial_case_id,
  penalty_type,
  amount,
  created_at,
  resolved_at
from public.penalties;

create or replace view public.current_penalties
with (security_invoker = true, security_barrier = true)
as
select *
from public.penalties
where trainer_id = public.current_trainer_id()
   or public.is_current_user_admin();

do $$
declare
  view_name text;
  view_names text[] := array[
    'current_activity_events',
    'current_coin_transactions',
    'current_parsed_saves',
    'current_penalties',
    'current_pokemon_flags',
    'current_purchases',
    'current_redemptions',
    'current_save_files',
    'current_team_locks',
    'current_trainer_flags',
    'current_trainer_profile',
    'current_trial_cases',
    'current_trial_votes',
    'public_activity_events',
    'public_coin_balances',
    'public_cup_matches',
    'public_cup_participants',
    'public_cup_standings',
    'public_cups',
    'public_division_memberships',
    'public_divisions',
    'public_hall_of_fame',
    'public_matchday_movements',
    'public_matchday_snapshots',
    'public_matchdays',
    'public_matches',
    'public_penalties',
    'public_season_config_versions',
    'public_season_player_stats',
    'public_season_players',
    'public_seasons',
    'public_shop_items',
    'public_shop_promotions',
    'public_team_locks',
    'public_trainer_flags',
    'public_trainers',
    'public_trial_cases'
  ];
begin
  foreach view_name in array view_names loop
    execute format('revoke all on table public.%I from public', view_name);

    if exists (select 1 from pg_roles where rolname = 'anon') then
      execute format('revoke all on table public.%I from anon', view_name);
    end if;

    if exists (select 1 from pg_roles where rolname = 'authenticated') then
      execute format('grant select on table public.%I to authenticated', view_name);
    end if;

    if exists (select 1 from pg_roles where rolname = 'service_role') then
      execute format('grant all privileges on table public.%I to service_role', view_name);
    end if;
  end loop;
end;
$$;

comment on view public.public_trainers is
  'Safe trainer projection. Hides auth_user_id, metadata and is_admin.';
comment on view public.public_team_locks is
  'Public Team Preview projection. Exposes public_team_snapshot only.';
comment on view public.current_team_locks is
  'Owner/admin TeamLock projection. Includes private_team_snapshot.';
comment on view public.public_shop_promotions is
  'Visible promotions only. Pending/future/cancelled promotions remain admin/server-only.';
comment on view public.public_coin_balances is
  'Public balance aggregate. Detailed coin_transactions remain owner/admin.';

commit;
-- ============================================================================
-- END 012_security_views.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 013_storage_policies.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 013_storage_policies: private raw-saves bucket access rules.
-- Supabase Cloud already owns storage.objects; keep this migration policy-only.

begin;

do $$
begin
  if exists (
    select 1
    from information_schema.tables
    where table_schema = 'storage'
      and table_name = 'objects'
  ) then
    execute 'drop policy if exists raw_saves_select_own_or_admin on storage.objects';
    execute 'drop policy if exists raw_saves_insert_own_or_admin on storage.objects';
    execute 'drop policy if exists raw_saves_update_own_or_admin on storage.objects';
    execute 'drop policy if exists raw_saves_delete_own_or_admin on storage.objects';

    execute $policy$
      create policy raw_saves_select_own_or_admin
      on storage.objects
      for select
      to authenticated
      using (
        bucket_id = 'raw-saves'
        and (
          public.is_current_user_admin()
          or split_part(name, '/', 1) = public.current_trainer_id()::text
        )
      )
    $policy$;

    execute $policy$
      create policy raw_saves_insert_own_or_admin
      on storage.objects
      for insert
      to authenticated
      with check (
        bucket_id = 'raw-saves'
        and (
          public.is_current_user_admin()
          or split_part(name, '/', 1) = public.current_trainer_id()::text
        )
      )
    $policy$;

    execute $policy$
      create policy raw_saves_update_own_or_admin
      on storage.objects
      for update
      to authenticated
      using (
        bucket_id = 'raw-saves'
        and (
          public.is_current_user_admin()
          or split_part(name, '/', 1) = public.current_trainer_id()::text
        )
      )
      with check (
        bucket_id = 'raw-saves'
        and (
          public.is_current_user_admin()
          or split_part(name, '/', 1) = public.current_trainer_id()::text
        )
      )
    $policy$;

    execute $policy$
      create policy raw_saves_delete_own_or_admin
      on storage.objects
      for delete
      to authenticated
      using (
        bucket_id = 'raw-saves'
        and (
          public.is_current_user_admin()
          or split_part(name, '/', 1) = public.current_trainer_id()::text
        )
      )
    $policy$;
  end if;
end;
$$;

commit;
-- ============================================================================
-- END 013_storage_policies.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 014_security_invoker_hardening.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 014_security_invoker_hardening: make client views use caller RLS and lock anon helper RPC access.

begin;

do $$
declare
  view_name text;
  view_names text[] := array[
    'current_activity_events',
    'current_coin_transactions',
    'current_parsed_saves',
    'current_penalties',
    'current_pokemon_flags',
    'current_purchases',
    'current_redemptions',
    'current_save_files',
    'current_team_locks',
    'current_trainer_flags',
    'current_trainer_profile',
    'current_trial_cases',
    'current_trial_votes',
    'public_activity_events',
    'public_coin_balances',
    'public_cup_matches',
    'public_cup_participants',
    'public_cup_standings',
    'public_cups',
    'public_division_memberships',
    'public_divisions',
    'public_hall_of_fame',
    'public_matchday_movements',
    'public_matchday_snapshots',
    'public_matchdays',
    'public_matches',
    'public_penalties',
    'public_season_config_versions',
    'public_season_player_stats',
    'public_season_players',
    'public_seasons',
    'public_shop_items',
    'public_shop_promotions',
    'public_team_locks',
    'public_trainer_flags',
    'public_trainers',
    'public_trial_cases'
  ];
begin
  foreach view_name in array view_names loop
    execute format(
      'alter view public.%I set (security_invoker = true, security_barrier = true)',
      view_name
    );
  end loop;
end;
$$;

revoke all on function public.current_auth_uid() from public;
revoke all on function public.current_trainer_id() from public;
revoke all on function public.is_current_user_admin() from public;
revoke all on function public.current_user_owns_trainer(uuid) from public;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on function public.current_auth_uid() from anon;
    revoke all on function public.current_trainer_id() from anon;
    revoke all on function public.is_current_user_admin() from anon;
    revoke all on function public.current_user_owns_trainer(uuid) from anon;
  end if;

  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    grant execute on function public.current_auth_uid() to authenticated;
    grant execute on function public.current_trainer_id() to authenticated;
    grant execute on function public.is_current_user_admin() to authenticated;
    grant execute on function public.current_user_owns_trainer(uuid) to authenticated;
  end if;

  if exists (select 1 from pg_roles where rolname = 'service_role') then
    grant execute on function public.current_auth_uid() to service_role;
    grant execute on function public.current_trainer_id() to service_role;
    grant execute on function public.is_current_user_admin() to service_role;
    grant execute on function public.current_user_owns_trainer(uuid) to service_role;
  end if;
end;
$$;

commit;
-- ============================================================================
-- END 014_security_invoker_hardening.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 015_public_trainers_visibility.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 015_public_trainers_visibility: keep the public trainer listing readable.

begin;

alter view public.public_trainers
set (security_invoker = false, security_barrier = true);

commit;
-- ============================================================================
-- END 015_public_trainers_visibility.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 016_public_team_locks_visibility.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 016_public_team_locks_visibility: keep the public team lock listing readable.

begin;

alter view public.public_team_locks
set (security_invoker = false, security_barrier = true);

commit;
-- ============================================================================
-- END 016_public_team_locks_visibility.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 017_public_coin_balances_visibility.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 017_public_coin_balances_visibility: keep the public coin balance aggregate readable.

begin;

alter view public.public_coin_balances
set (security_invoker = false, security_barrier = true);

commit;
-- ============================================================================
-- END 017_public_coin_balances_visibility.sql
-- ============================================================================

-- ============================================================================
-- BEGIN 018_public_views_visibility.sql
-- ============================================================================
-- PokeApp Supabase V2 security layer.
-- 018_public_views_visibility: keep public projections readable while private projections stay invoker-based.

begin;

do $$
declare
  view_name text;
  view_names text[] := array[
    'public_activity_events',
    'public_coin_balances',
    'public_cup_matches',
    'public_cup_participants',
    'public_cup_standings',
    'public_cups',
    'public_division_memberships',
    'public_divisions',
    'public_hall_of_fame',
    'public_matchday_movements',
    'public_matchday_snapshots',
    'public_matchdays',
    'public_matches',
    'public_penalties',
    'public_season_config_versions',
    'public_season_player_stats',
    'public_season_players',
    'public_seasons',
    'public_shop_items',
    'public_shop_promotions',
    'public_team_locks',
    'public_trainer_flags',
    'public_trainers',
    'public_trial_cases'
  ];
begin
  foreach view_name in array view_names loop
    execute format(
      'alter view public.%I set (security_invoker = false, security_barrier = true)',
      view_name
    );
  end loop;
end;
$$;

commit;
-- ============================================================================
-- END 018_public_views_visibility.sql
-- ============================================================================
