from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
V2_DIR = ROOT / "supabase" / "v2"
MIGRATIONS_DIR = V2_DIR / "migrations"
BOOTSTRAP_SQL = V2_DIR / "bootstrap.sql"

EXPECTED_MIGRATIONS = [
    "001_core.sql",
    "002_seasons.sql",
    "003_league.sql",
    "004_shop.sql",
    "005_saves.sql",
    "006_activity_hall.sql",
    "007_competitions.sql",
    "008_indexes.sql",
    "009_seed.sql",
]

FORBIDDEN_TOKENS = [
    "drop table",
    "drop schema",
    "reset_dev.sql",
]


def _migration_files() -> list[Path]:
    files = sorted(MIGRATIONS_DIR.glob("*.sql"))
    names = [path.name for path in files]
    if names != EXPECTED_MIGRATIONS:
        raise SystemExit(
            "Unexpected Supabase V2 migration set.\n"
            f"Expected: {EXPECTED_MIGRATIONS}\n"
            f"Found:    {names}"
        )
    return files


def render_bootstrap() -> str:
    sections = [
        "-- ONLY FOR EMPTY POKEAPP V2 DATABASE.",
        "--",
        "-- Generated operational bootstrap for Supabase SQL Editor.",
        "-- Source of truth: supabase/v2/migrations/001_core.sql through 009_seed.sql.",
        "-- Do not edit this file manually; regenerate it with:",
        "--   py tools/generate_supabase_v2_bootstrap.py",
        "--",
        "-- This file intentionally excludes the destructive development reset.",
        "-- It contains no destructive reset statements and is not a reset script.",
        "",
    ]

    for path in _migration_files():
        sql = path.read_text(encoding="utf-8").strip()
        lowered = sql.lower()
        for token in FORBIDDEN_TOKENS:
            if token in lowered:
                raise SystemExit(f"Refusing to include forbidden token {token!r} from {path}")
        sections.append("-- ============================================================================")
        sections.append(f"-- BEGIN {path.name}")
        sections.append("-- ============================================================================")
        sections.append(sql)
        sections.append("-- ============================================================================")
        sections.append(f"-- END {path.name}")
        sections.append("-- ============================================================================")
        sections.append("")

    return "\n".join(sections).rstrip() + "\n"


def main() -> int:
    BOOTSTRAP_SQL.write_text(render_bootstrap(), encoding="utf-8", newline="\n")
    print(f"Generated {BOOTSTRAP_SQL.relative_to(ROOT)} from {len(EXPECTED_MIGRATIONS)} migrations.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
